feat: update podspec to 13.0.3 with StraaSStarscream 3.0.8 got error
 -> StraaS-Socket.IO-Client-Swift (13.0.3)
    - WARN  | source: The version should be included in the Git tag.
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Planning build
    - NOTE  | xcodebuild:  note: Constructing build description
    - NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')
    - ERROR | xcodebuild:  /Users/allenandkim/Documents/Bitbucket/socket.io-client-swift/Source/SocketIO/Engine/SocketEngine.swift:27:8: error: no such module 'Starscream'

Pods workspace available at `/var/folders/8h/j0__hs5s7jg4_832rcw9cfjc0000gn/T/CocoaPods-Lint-20190829-72369-5wr2gi-StraaS-Socket.IO-Client-Swift/App.xcworkspace` for inspection.

[!] StraaS-Socket.IO-Client-Swift did not pass validation, due to 2 errors.